
run:
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - deadcode
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
  disable-all: true
  fast: false

issues:
  fix: false

service:
  golangci-lint-version: 1.37.1