// Code generated by MockGen. DO NOT EDIT.
// Source: ../../validation.go

// Package validationmocks is a generated GoMock package.
package validationmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSimpleValidator is a mock of SimpleValidator interface.
type MockSimpleValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSimpleValidatorMockRecorder
}

// MockSimpleValidatorMockRecorder is the mock recorder for MockSimpleValidator.
type MockSimpleValidatorMockRecorder struct {
	mock *MockSimpleValidator
}

// NewMockSimpleValidator creates a new mock instance.
func NewMockSimpleValidator(ctrl *gomock.Controller) *MockSimpleValidator {
	mock := &MockSimpleValidator{ctrl: ctrl}
	mock.recorder = &MockSimpleValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSimpleValidator) EXPECT() *MockSimpleValidatorMockRecorder {
	return m.recorder
}

// Valid mocks base method.
func (m *MockSimpleValidator) Valid() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Valid")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Valid indicates an expected call of Valid.
func (mr *MockSimpleValidatorMockRecorder) Valid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Valid", reflect.TypeOf((*MockSimpleValidator)(nil).Valid))
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockValidator) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockValidatorMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidator)(nil).Validate))
}
