// Code generated by MockGen. DO NOT EDIT.
// Source: ../mockable.go

// Package injectmocks is a generated GoMock package.
package injectmocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	inject "github.com/ibrt/golang-lib/inject"
)

// MockTestInitializer is a mock of TestInitializer interface.
type MockTestInitializer struct {
	ctrl     *gomock.Controller
	recorder *MockTestInitializerMockRecorder
}

// MockTestInitializerMockRecorder is the mock recorder for MockTestInitializer.
type MockTestInitializerMockRecorder struct {
	mock *MockTestInitializer
}

// NewMockTestInitializer creates a new mock instance.
func NewMockTestInitializer(ctrl *gomock.Controller) *MockTestInitializer {
	mock := &MockTestInitializer{ctrl: ctrl}
	mock.recorder = &MockTestInitializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestInitializer) EXPECT() *MockTestInitializerMockRecorder {
	return m.recorder
}

// Initialize mocks base method.
func (m *MockTestInitializer) Initialize(ctx context.Context) (inject.Injector, inject.Releaser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(inject.Injector)
	ret1, _ := ret[1].(inject.Releaser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Initialize indicates an expected call of Initialize.
func (mr *MockTestInitializerMockRecorder) Initialize(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockTestInitializer)(nil).Initialize), ctx)
}

// MockTestInjector is a mock of TestInjector interface.
type MockTestInjector struct {
	ctrl     *gomock.Controller
	recorder *MockTestInjectorMockRecorder
}

// MockTestInjectorMockRecorder is the mock recorder for MockTestInjector.
type MockTestInjectorMockRecorder struct {
	mock *MockTestInjector
}

// NewMockTestInjector creates a new mock instance.
func NewMockTestInjector(ctrl *gomock.Controller) *MockTestInjector {
	mock := &MockTestInjector{ctrl: ctrl}
	mock.recorder = &MockTestInjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestInjector) EXPECT() *MockTestInjectorMockRecorder {
	return m.recorder
}

// Inject mocks base method.
func (m *MockTestInjector) Inject(ctx context.Context) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inject", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inject indicates an expected call of Inject.
func (mr *MockTestInjectorMockRecorder) Inject(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inject", reflect.TypeOf((*MockTestInjector)(nil).Inject), ctx)
}

// MockTestReleaser is a mock of TestReleaser interface.
type MockTestReleaser struct {
	ctrl     *gomock.Controller
	recorder *MockTestReleaserMockRecorder
}

// MockTestReleaserMockRecorder is the mock recorder for MockTestReleaser.
type MockTestReleaserMockRecorder struct {
	mock *MockTestReleaser
}

// NewMockTestReleaser creates a new mock instance.
func NewMockTestReleaser(ctrl *gomock.Controller) *MockTestReleaser {
	mock := &MockTestReleaser{ctrl: ctrl}
	mock.recorder = &MockTestReleaserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestReleaser) EXPECT() *MockTestReleaserMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockTestReleaser) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockTestReleaserMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockTestReleaser)(nil).Release))
}
