// Code generated by MockGen. DO NOT EDIT.
// Source: ../mockable.go

// Package runnersmocks is a generated GoMock package.
package runnersmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTestFunc is a mock of TestFunc interface.
type MockTestFunc struct {
	ctrl     *gomock.Controller
	recorder *MockTestFuncMockRecorder
}

// MockTestFuncMockRecorder is the mock recorder for MockTestFunc.
type MockTestFuncMockRecorder struct {
	mock *MockTestFunc
}

// NewMockTestFunc creates a new mock instance.
func NewMockTestFunc(ctrl *gomock.Controller) *MockTestFunc {
	mock := &MockTestFunc{ctrl: ctrl}
	mock.recorder = &MockTestFuncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestFunc) EXPECT() *MockTestFuncMockRecorder {
	return m.recorder
}

// Func mocks base method.
func (m *MockTestFunc) Func() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Func")
	ret0, _ := ret[0].(error)
	return ret0
}

// Func indicates an expected call of Func.
func (mr *MockTestFuncMockRecorder) Func() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Func", reflect.TypeOf((*MockTestFunc)(nil).Func))
}
